apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocp-cli1

resources:
- 01-namespace.yaml
- 02-cluster-deployment.yaml
- 03-agent-cluster-install.yaml
- 04-infra-env.yaml
- hosts/host1
- hosts/host2
- hosts/host3

commonLabels:
  app: ztp-cluster-install
  cluster-name: ocp-cli1
  site: site-cliente-1
