apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace padr√£o aplicado a todos os manifests
namespace: ztp-cluster

# Manifests principais do cluster
resources:
- 01-namespace.yaml
- 02-cluster-deployment.yaml
- 03-agent-cluster-install.yaml
- 04-infra-env.yaml
- hosts/pmalpdvviro0001
- hosts/pmalpdvviro0002
- hosts/pmalpdvviro0003
- hosts/pmalpdvviro0004
- hosts/pmalpdvviro0005

# Labels comuns para facilitar filtragem
commonLabels:
  app: ztp-cluster-install
  cluster-name: sno-cluster2
  site: site-cliente-1
